#!/usr/bin/bash
scores="score_history1000000"
biggest=1000000   # maximum number possible
guess=0                   # guessed by player
guesses=1                # number of guesses made
number=$(($$ % $biggest))  # random number, between 1 and $biggest
echo "***LET'S PLAY!***"
echo "Choose a number from 1 - 1 000 000: "
read guess 

while (( number!=guess ))
do 
	if (( guess<number ))
	then 
		echo "Our secret number is bigger"
	elif (( guess>number ))
	then 
		echo "Our secret number is smaller"
	else 
		sleep 1
	fi
	echo "Try again!! Choose from 1 - 1 000 000: "
        read guess
	(( guesses++ ))
done      
echo "Correct! You guessed $number in $guesses guesses"
echo "Please enter your name: "
read name
echo $name $guesses >> $scores
cat $scores
